version: "3.9"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=database://oss:svXsnZVVUUybzNwgdVGWJpgYFzchBw@postgres:5432/oss
      - REDIS_URL=redis://redis:6379
    ports:
      - "8081:8080"
    depends_on:
      - database
      - redis
  frontend:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend

  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=$PASSWD_ROOT
      - ROOT_PASSWORD=$PASSWD_ROOT
      - MYSQL_USER=$USER
      - MYSQL_PASSWORD=$PASSWD
      - MYSQL_DATABASE=$NAME
    volumes:
      - /data:/var/lib/mysql
    ports:
      - 3306:3306
  
  redis:
    image: redis
    command: redis-server
    ports:
      - "6384:6379"
    volumes:
      - redisdata:/data
volumes:
  pgdata:
  redisdata:
