// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"oss-backend/internal/config"
	"oss-backend/internal/persistence/postgres"
	"oss-backend/internal/service/auth"
	"oss-backend/internal/service/aws/media"
	"oss-backend/internal/service/dish"
	"oss-backend/internal/service/httpserver"
	"oss-backend/internal/service/order"
	"oss-backend/internal/service/product"
	"oss-backend/internal/service/shoppingCard"
	"oss-backend/internal/service/tag"
	"oss-backend/internal/service/user"
)

// Injectors from wire.go:

func Up() (*Dependencies, error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	configPostgres := getPostgresConfig(configConfig)
	postgresPostgres := postgres.New(configPostgres)
	userService := user.New(postgresPostgres)
	service := auth.New(configConfig, userService, postgresPostgres) 
	mediaService, err := media.New(configConfig)
	if err != nil {
		return nil, err
	}

	productService := product.New(postgresPostgres)
	cardService := shoppingCard.New(postgresPostgres)
	orderService := order.New(postgresPostgres)

	if err != nil {
		return nil, err
	}

	tagService := tag.New(postgresPostgres)
	dishService := dish.New(postgresPostgres)
	httpServer := httpserver.New(configConfig, service, userService, mediaService, productService, tagService, dishService, cardService, orderService)
	dependencies := NewDependencies(configConfig, httpServer, service, userService, postgresPostgres)
	return dependencies, nil
}

// wire.go:

func getPostgresConfig(cfg config.Config) config.Postgres {
	return cfg.Postgres
}
